### ISSUE TITLE
Pluralization of word `research`

### ISSUE THREAD

**Issue by Borkache** [doctrine/inflector#166] opened 2020-05-30 07:29 UTC
During the update from 1.3.1 to 1.4.3 pluralization of word `research` to `researches` was ruined. Now it's `research` for both conditions

**Comment by greg0ire** [comment] 2020-05-30 08:03
Duplicate of #156

**Closed** 2020-05-30 08:03 UTC
Labels: Won't Fix

**Comment by greg0ire** [comment] 2020-05-30 08:05
Please have a look at related issues.

**Comment by GrahamCampbell** [comment] 2020-05-30 08:10
`research` is the correct pluralisation, 1.3.1 was pluralising it incorrectly.
